model:
  user:
    name:
      max: 140
    email:
      max: 140
    password:
      min: 6
session:
  remember: 1
rows: 50
avatar_size: 50
avatar_follow: 30
reset_password_timeout_hours.ago: 2
content_max: 140
picture_size: 5
picture_height: 400
picture_width: 400
picture_type: "image/jpeg,image/gif,image/png"
